# Generated by Django 3.1 on 2020-09-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_company_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_contacts',
            new_name='Company_Contact',
        ),
    ]
