# Generated by Django 3.1 on 2020-09-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200901_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_Contact',
            new_name='CompanyContact',
        ),
    ]
