# Generated by Django 3.1 on 2020-09-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='features',
        ),
    ]
